### ISSUE TITLE
Unable to see created tables in Docker container

### ISSUE THREAD

**Issue by BojanKomazec** [better/jsonschema2db#27]
As an exercise, I want to query tables created in Docker container upon running tests. I modified Docker file from this repo by adding `&& /bin/bash` at `CMD` to prevent container terminating as soon as tests are executed.

Upon starting the container and looking its logs (`docker logs <id>`) I can see the terminal output and that tests are passing. If I connect to container (`$ docker exec -it <id> bash`) I can see (via `psql -l`) that expected database (`jsonschema2db-test`) is created, with `app` as owner but upon connecting to that database (`psql jsonschema2db-test`) listing all tables in psql terminal (`\dt`) returns `No relations found`. 

How can I verify that expected tables are indeed created in DB? Am I doing anything wrong in this process? Thanks

**Comment by erikbern** [comment]
if the tests succeed then the tables would definitely be created. maybe they are created within a transaction and that's why you don't see them? not sure

**Comment by BojanKomazec** [comment]
Hi Erik,

Thank you very much for your fast reply and help. I modified `test.py` so it commits transaction and now after making sure that in my psql commands I don't use the default, but the schema set in the code (`schm`), I can see tables and their content in psql terminal.
