### ISSUE TITLE
Very complex json schema

### ISSUE THREAD

**Issue by AbdelrahmanAlhaj** [better/jsonschema2db#37]
Is there any way to convert very complex (json schema) like in the link bellow:

https://drive.google.com/file/d/128IAM71qQXHRVGzxE8uCy9WTte-RliLW/view?usp=sharing

because when I convert it using your library it's giving error for type (array,['string', 'null'])

**Comment by gerbrand** [comment]
I think this is related to #25

**Comment by AbdelrahmanAlhaj** [comment]
> I think this is related to #25

Yes, it is. Thank you
