### ISSUE TITLE
feature request -- add snowflake implementation

### ISSUE THREAD

**Issue by bgilbert-fetchrewards** [better/jsonschema2db#40]
I'm working on a Snowflake implementation on a local fork and wanted to know if you all were open to outside contributors. If so, do you have a contribution document / guidelines?

JSONSchemaToSnowflake execution currently looks like
```python
schema = json.load(open('item_schema.json'))
translator = JSONSchemaToSnowflake(
    schema,
    schema_namespace='sch',
    item_col_name='_item_id',
    item_col_type='string',
)

SNOWFLAKE_CLIENT.cursor().execute('alter session set quoted_identifiers_ignore_case = true')
translator.create_tables(SNOWFLAKE_CLIENT)
payload = json.load(open('item_payload.json'))
translator.insert_items(SNOWFLAKE_CLIENT, [
    ('_item_id_1232', payload)
])
```

**Comment by erikbern** [comment]
sure, happy to take a pull request!

**Comment by bgilbert-fetchrewards** [comment]
@erikbern I'm going to close, I ended up having to change more than I expected to handle complex arrays that were being dropped with the current version. It's starting to look a little over-engineered for a public repo.

I also threw [black](https://github.com/psf/black) the codebase and it reformatted just about everything 💀 

tyvm for the repo!

**Comment by erikbern** [comment]
ok, that's too bad, i'd love to look at it at some later point!

**Comment by bgilbert-fetchrewards** [comment]
Threw it up. If you have any notes on how to handle complex json schema more intelligently than I have, I'd be very interested to hear your thoughts. Unfortunately there were no `patternProperties` in my json schema(s), so I will have to flatten a Snowflake variant with another tool or add another loop.
